run:
  skip-dirs:
    - rev-menubar

linters-settings:
  gosec:
    confidence: low
  godot:
    exclude:
      # Exclude swagger comments
      - "@"
  gci:
    skip-generated: true
  cyclop:
    max-complexity: 15
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake
        xml: snake

linters:
  enable:
    - asasalint
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosimple
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
#   - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - typecheck
    - usestdlibvars
    - unparam
    - unused
    - whitespace
